image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: source\Sem02Test01\Sem02Test01\Sem02Test01.sln
  
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%